/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DimensionsRouteImport } from './routes/dimensions'
import { Route as FoundingRouteImport } from './routes/founding'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ReserveSuccessRouteImport } from './routes/reserve.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionsRoute = DimensionsRouteImport.update({
  id: '/dimensions',
  path: '/dimensions',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingRoute = FoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveSuccessRoute = ReserveSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ReserveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/reserve'
    | '/reserve/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/reserve'
    | '/reserve/success'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/reserve'
    | '/reserve/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DimensionsRoute: typeof DimensionsRoute
  FoundingRoute: typeof FoundingRoute
  NetworkRoute: typeof NetworkRoute
  ReserveRoute: typeof ReserveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensions': {
      id: '/dimensions'
      path: '/dimensions'
      fullPath: '/dimensions'
      preLoaderRoute: typeof DimensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding': {
      id: '/founding'
      path: '/founding'
      fullPath: '/founding'
      preLoaderRoute: typeof FoundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/success': {
      id: '/reserve/success'
      path: '/success'
      fullPath: '/reserve/success'
      preLoaderRoute: typeof ReserveSuccessRouteImport
      parentRoute: typeof ReserveRoute
    }
  }
}

interface ReserveRouteChildren {
  ReserveSuccessRoute: typeof ReserveSuccessRoute
}

const ReserveRouteChildren: ReserveRouteChildren = {
  ReserveSuccessRoute: ReserveSuccessRoute,
}

const ReserveRouteWithChildren =
  ReserveRoute._addFileChildren(ReserveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DimensionsRoute: DimensionsRoute,
  FoundingRoute: FoundingRoute,
  NetworkRoute: NetworkRoute,
  ReserveRoute: ReserveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
