/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as DimensionsRouteImport } from './routes/dimensions'
import { Route as FoundingRouteImport } from './routes/founding'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReserveSuccessRouteImport } from './routes/reserve.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionsRoute = DimensionsRouteImport.update({
  id: '/dimensions',
  path: '/dimensions',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingRoute = FoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveSuccessRoute = ReserveSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ReserveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/qa': typeof QaRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/review': typeof ReviewRoute
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/qa': typeof QaRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/review': typeof ReviewRoute
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/dimensions': typeof DimensionsRoute
  '/founding': typeof FoundingRoute
  '/network': typeof NetworkRoute
  '/qa': typeof QaRoute
  '/reserve': typeof ReserveRouteWithChildren
  '/review': typeof ReviewRoute
  '/reserve/success': typeof ReserveSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/compare'
    | '/consult'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/qa'
    | '/reserve'
    | '/review'
    | '/reserve/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/compare'
    | '/consult'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/qa'
    | '/reserve'
    | '/review'
    | '/reserve/success'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/compare'
    | '/consult'
    | '/dimensions'
    | '/founding'
    | '/network'
    | '/qa'
    | '/reserve'
    | '/review'
    | '/reserve/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CompareRoute: typeof CompareRoute
  ConsultRoute: typeof ConsultRoute
  DimensionsRoute: typeof DimensionsRoute
  FoundingRoute: typeof FoundingRoute
  NetworkRoute: typeof NetworkRoute
  QaRoute: typeof QaRoute
  ReserveRoute: typeof ReserveRouteWithChildren
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensions': {
      id: '/dimensions'
      path: '/dimensions'
      fullPath: '/dimensions'
      preLoaderRoute: typeof DimensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding': {
      id: '/founding'
      path: '/founding'
      fullPath: '/founding'
      preLoaderRoute: typeof FoundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/success': {
      id: '/reserve/success'
      path: '/success'
      fullPath: '/reserve/success'
      preLoaderRoute: typeof ReserveSuccessRouteImport
      parentRoute: typeof ReserveRoute
    }
  }
}

interface ReserveRouteChildren {
  ReserveSuccessRoute: typeof ReserveSuccessRoute
}

const ReserveRouteChildren: ReserveRouteChildren = {
  ReserveSuccessRoute: ReserveSuccessRoute,
}

const ReserveRouteWithChildren =
  ReserveRoute._addFileChildren(ReserveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CompareRoute: CompareRoute,
  ConsultRoute: ConsultRoute,
  DimensionsRoute: DimensionsRoute,
  FoundingRoute: FoundingRoute,
  NetworkRoute: NetworkRoute,
  QaRoute: QaRoute,
  ReserveRoute: ReserveRouteWithChildren,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
